
server: 192.168.56.10
setup:
  field_mapping:
    clientname: '主机名称*'
    important_system_flag: '是否为重要信息系统'
    important_data_flag: '是否保存外部客户原始凭证数据的系统'
    datatype: '数据类型*'
    os: '操作系统'
    path: '文件备份路径*'
    start_time: '备份开始时间'
    description: '备份数据说明'
